version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: secureauth
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  # Producción
  app:
    build:
      context: .
      target: production
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/secureauth?schema=public
      - PORT=3000
    command: >
      sh -c "
        npx prisma migrate deploy &&
        node dist/server.js
      "

  # Desarrollo
  app-dev:
    build:
      context: .
      target: dev
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/secureauth?schema=public
      - PORT=3000
    volumes:
      - ./:/app
    command: >
      sh -c "
        npx prisma migrate dev --name init &&
        npm run dev
      "

volumes:
  db_data:
  pgadmin_data: